from python:3.8

ARG PUID=1000
RUN useradd -u "${PUID}" -m raccoon ##setting user for raccoon

##back to original user
USER raccoon 

WORKDIR ${HOME}

## RUN cd /home  \  ##preparing internal filestructure
#	&& MKDIR ${RACC_ROOT_DIR} \
#	&& MKDIR ${RACC_DL_DIR} \
#	&& MKDIR ${RACC_TEMP_DIR} \
#	&& MKDIR ${RACC_BIND_DIR} \  ##Theoretically this will only be used for debug / ftp / samba in edge cases. 
#	&& cd ${RACC_ROOT_DIR}

##copy python files and dependencies into root app folder
COPY /source/.  ${RACC_ROOT_DIR}

## execute dependencies
RUN pip install -r requirements.txt

# The `|| exit 1` isn't required but it's good practice anyway.
HEALTHCHECK CMD discordhealthcheck || exit 1

CMD ["python", "/home/raccoon/raccoon.py"]