version: '3.3'
services:
    python:
        volumes:
            - './python:/home/'
#            - './python/app:/home/raccoon/bind/'
        build: .
        image: silentmecha/raccoon:latest
        restart: unless-stopped
        command: bash
        stdin_open: true
        tty: true